#!/bin/sh
git clone https://github.com/mileszs/ack.vim.git ~/.vim/bundle/ack.vim
git clone https://github.com/w0rp/ale.git ~/.vim/bundle/ale
git clone https://github.com/skywind3000/asyncrun.vim.git ~/.vim/bundle/asyncrun.vim
git clone https://github.com/metakirby5/codi.vim.git ~/.vim/bundle/codi.vim
git clone https://github.com/kien/ctrlp.vim.git ~/.vim/bundle/ctrlp.vim
git clone https://github.com/editorconfig/editorconfig-vim.git ~/.vim/bundle/editorconfig-vim
git clone https://github.com/morhetz/gruvbox.git ~/.vim/bundle/gruvbox
git clone https://github.com/wikitopian/hardmode.git ~/.vim/bundle/hardmode
git clone https://github.com/Valloric/MatchTagAlways.git ~/.vim/bundle/MatchTagAlways
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
git clone https://github.com/ShuaiHsunLee/ranger.vim.git ~/.vim/bundle/ranger.vim
git clone https://github.com/ervandew/supertab.git ~/.vim/bundle/supertab
git clone https://github.com/godlygeek/tabular.git ~/.vim/bundle/tabular
git clone https://github.com/majutsushi/tagbar.git ~/.vim/bundle/tagbar
git clone https://github.com/vim-airline/vim-airline.git ~/.vim/bundle/vim-airline
git clone https://github.com/vim-airline/vim-airline-themes.git ~/.vim/bundle/vim-airline-themes
git clone https://github.com/kalekundert/vim-coiled-snake.git ~/.vim/bundle/vim-coiled-snake
git clone https://github.com/tpope/vim-commentary.git ~/.vim/bundle/vim-commentary
git clone https://github.com/ap/vim-css-color.git ~/.vim/bundle/vim-css-color
git clone https://github.com/tpope/vim-fugitive.git ~/.vim/bundle/vim-fugitive
git clone https://github.com/airblade/vim-gitgutter.git ~/.vim/bundle/vim-gitgutter
git clone https://github.com/takac/vim-hardtime.git ~/.vim/bundle/vim-hardtime
git clone https://github.com/nathanaelkane/vim-indent-guides.git ~/.vim/bundle/vim-indent-guides
git clone https://github.com/henrik/vim-indexed-search.git ~/.vim/bundle/vim-indexed-search
git clone https://github.com/euclio/vim-markdown-composer.git ~/.vim/bundle/vim-markdown-composer
git clone https://github.com/terryma/vim-multiple-cursors.git ~/.vim/bundle/vim-multiple-cursors
git clone https://github.com/pangloss/vim-javascript ~/.vim/bundle/vim-javascript
git clone https://github.com/tpope/vim-repeat.git ~/.vim/bundle/vim-repeat
git clone https://github.com/tpope/vim-rhubarb.git ~/.vim/bundle/vim-rhubarb
git clone https://github.com/tpope/vim-surround.git ~/.vim/bundle/vim-surround
git clone https://github.com/christoomey/vim-system-copy.git ~/.vim/bundle/vim-system-copy
git clone https://github.com/dhruvasagar/vim-table-mode.git ~/.vim/bundle/vim-table-mode
git clone https://github.com/vimwiki/vimwiki.git ~/.vim/bundle/vimwiki
git clone https://github.com/sjl/vitality.vim.git ~/.vim/bundle/vitality.vim
git clone https://github.com/simeji/winresizer.git ~/.vim/bundle/winresizer
git clone https://github.com/Valloric/YouCompleteMe.git ~/.vim/bundle/YouCompleteMe
git clone https://github.com/kien/rainbow_parentheses.vim.git ~/.vim/bundle/rainbow_parentheses.vim
git clone https://github.com/mhinz/vim-startify.git ~/.vim/bundle/vim-startify
git clone https://github.com/easymotion/vim-easymotion.git ~/.vim/bundle/vim-easymotion
